# Default colors
[colors.primary]
background = '#232627'
foreground = '#fcfcfc'

dim_foreground = '#eff0f1'
bright_foreground = '#ffffff'

# Normal colors
[colors.normal]
black = '#232627'
red = '#ed1515'
green = '#11d116'
yellow = '#f67400'
blue = '#1d99f3'
magenta = '#9b59b6'
cyan = '#1abc9c'
white = '#fcfcfc'

# Bright colors
[colors.bright]
black = '#7f8c8d'
red = '#c0392b'
green = '#1cdc9a'
yellow = '#fdbc4b'
blue = '#3daee9'
magenta = '#8e44ad'
cyan = '#16a085'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#31363b'
red = '#783228'
green = '#17a262'
yellow = '#b65619'
blue = '#1b668f'
magenta = '#614a73'
cyan = '#186c60'
white = '#63686d'

[selection]
save_to_clipboard = true

[shell]
args = ["-c", "~/.dotfiles/single.sh"]
program = "/bin/bash"

[window]
startup_mode = "Windowed"

[font]
size = 16

[font.bold]
family = "MonoLisa Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font Mono"
style = "Regular"
